#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")
Import("env_modules")

env_pc = env_modules.Clone()

if env.editor_build:
    env_pc.add_source_files(env.modules_sources, "*.cpp")
